spring:
  profiles:
    active:
    - ${AMBIENTE:dev} 
    
primary:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: 
    driverClassName: org.h2.Driver
    
#secondary:
#  datasource:
#    jdbcUrl: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
#    username: user
#    password: 
#    driverClassName: org.h2.Driver
    
spring.main.allow-bean-definition-overriding: true

---
spring: 
  profiles:
  - test
  
secondary:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: 
    driverClassName: org.h2.Driver
