spring:
  profiles:
    active:
    - ${AMBIENTE:dev} 
  jpa:
    database: default
    properties:
      hibernate:
#        show_sql: true
        globally_quoted_identifiers: true
#        dialect: org.hibernate.dialect.OracleDialect
  main.allow-bean-definition-overriding: true
    
primary:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: 
    driverClassName: org.h2.Driver
    
#secondary:
#  datasource:
#    jdbcUrl: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
#    username: user
#    password: 
#    driverClassName: org.h2.Driver

---
spring: 
  profiles:
  - test
  
secondary:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: 
    driverClassName: org.h2.Driver
